// tslint:disable-next-line:typedef
export const RootType = {
    UPDATE_USER:"UPDATE_USER",
    DELETE_USER:"DELETE_USER",
    SET_SYSTEMPARAM:"SET_SYSTEMPARAM",
    SET_INTERFACESYSTYPEBOH:"SET_INTERFACESYSTYPEBOH",
    SET_MATERIALSETTING:"SET_MATERIALSETTING",
};
export default RootType;