const CACHE_KEY = {
    // 订货新增
    "ORDER_ADDINFO":"ORDER_ADDINFO",
    'ORDER_ADDBEFOREINFO':"ORDER_ADDBEFOREINFO",
    'ORDER_CONTAINTIME':"ORDER_CONTAINTIME",
    //收货新增
    "RECEIVE_ADDINFO":"RECEIVE_ADDiNFO",
    "RECEIVE_ADDBEFOREINFO":"RECEIVEBEFOREINFO",
    "RECEIVE_BILLTYPE":"RECEIVE_BILLTYPE",//收货单据区别
    "RECEIVE_DETAILLIST":"RECEIVE_DETAILLIST",//收货单据详情
    "RECEIVE_SEARCH":"RECEIVE_SEARCH",//收货搜索条件
    //库存初始化新增
    'INITSTOCK_ADDINFO':"INITSTOCK_ADDINFO",  
    "INITSTOCK_ADDBEFOREINFO":"INITSTOCK_ADDBEFOREINFO",
    "INITSTOCK_SETTING":"INITSTOCK_SETTING",
    "INITSTOCK_DETAILLIST":"INITSTOCK_DETAILLIST",
    "INITSTOCK_SEARCH":"INITSTOCK_SEARCH",//订货搜索条件
    // 盘库模块
    "INVENTORY_LIST":"INVENTORY_LIST",  //盘库首页
    "INVENTORY_DETAILS":"INVENTORY_DETAILS",  //盘库详情
    "INVENTORY_RESULT":"INVENTORY_RESULT", //盘库搜索结果
    "INVENTORY_TYPE":"INVENTORY_TYPE",  //盘库类型
    "ADDINVENTORY":"ADDINVENTORY",
    "TEMPLATE_NAME":"TEMPLATE_NAME",  //盘库方式
    "ADDBEFORE_INVENTORY":"ADDBEFORE_INVENTORY", //新增盘库单
    "TEMPLATEIMPORT":"TEMPLATEIMPORT", //导入模板
    //调拨模块
    "ALLOTMENT_ADDINFO":"ALLOTMENT_ADDINFO",
    "ALLOTMENT_ADDBEFOREINFO":"ALLOTMENT_ADDBEFOREINFO",
    "ALLOTMENT_DETAILLIST":"ALLOTMENT_DETAILLIST",
    "ALLOTMENT_SEARCH":"ALLOTMENT_SEARCH",
    //损溢模块
    "SPILLEDSHEET_ADDINFO":"SPILLEDSHEET_ADDINFO",//添加损溢单
    "SPILLED_ADDBEFOREINFO":"SPILLED_ADDBEFOREINFO",
    "SPILLEDSHEET_SEARCH":"SPILLEDSHEET_SEARCH",  //查询损溢单
    //店内调拨模块
    "INSTOREALLOT_ADDINFO":"INSTOREALLOT_ADDINFO",
    "INSTOREALLOT_ADDBEFOREINFO":"INSTOREALLOT_ADDBEFOREINFO",
    "INSTOREALLOT_DETAILLIST":"INSTOREALLOT_DETAILLIST",
    "INSTOREALLOT_SEARCH":"INSTOREALLOT_SEARCH",
    //店间平调模块
    'STOREALLOT_ADDINFO':"STOREALLOT_ADDINFO",
    "STOREALLOT_ADDBEFOREINFO":"STOREALLOT_ADDBEFOREINFO",
    "STOREALLOT_DETAILLIST":"STOREALLOT_DETAILLIST",
    "STOREALLOT_SEARCH":"STOREALLOT_SEARCH"
}
export default CACHE_KEY;