
export const ReceiveGoodType = {
    // UPDATE_GOODLIST:"UPDATE_GOODlIST"
    // ADD_RECEIVEGOODINFO:'ADD_RECEIVEGOODINFO',
    // BEFORE_ADDRECEIVEGOODINFO:"BEFORE_ADDRECEIVEGOODINFO"
};
export default ReceiveGoodType;