
export const initStockType = {
    // ADD_INITSTOCKINFO:'ADD_INITSTOCKINFO',
    // ADD_BEFOREINITSTOCKINFO:'ADD_BEFOREINITSTOCKINFO',
    IS_FIRSTSTORE: 'IS_FIRSTSTORE',
};
export default initStockType;