
export const PublicAddGoodType = {
    UPDATE_ADDGOODLIST:"UPDATE_GOODlIST",//
    UPDATE_SELECTEDGOOD:'UPDATE_SELECTEDGOOD',//去提交的货品存储
    ADD_BILLINFO:"ADD_BILLINFI",
    ADD_BEFOREBILLINFO:"ADD_BEFOREBILLINFO"
};
export default PublicAddGoodType;